name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build the docker containers
        run: docker-compose up -d
      
      - name: Docker ps
        run: docker ps

      - name: Run Unit Tests
        run: docker exec deno deno test tests/unit_tests.ts --allow-net

      - name: Run End To End Tests
        run: docker exec deno deno test tests/end_to_end_tests.ts --allow-net

