name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: v1.x
      
      - name: Build the docker containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      
      - name: tests
        run: docker exec deno deno test --allow-net

